apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: systi2ogj-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-16eaf4105a.osbn.p3.openshiftapps.com/rhtap/rhtap-qe:625f4df1056d093917f47531a0c42190940d4ae6@sha256:1380cb172ffbd1b0f1615c82bb9590aa88b4ff997e359a1160a405cfd18c98bd
          name: container-image
